using System.Globalization;
using Microsoft.Extensions.Localization;

namespace GenoCRM.Services.Localization;

public class CountryService : ICountryService
{
    private readonly IStringLocalizer<CountryService> _localizer;
    
    public CountryService(IStringLocalizer<CountryService> localizer)
    {
        _localizer = localizer;
    }
    
    public Dictionary<string, string> GetCountries()
    {
        var countries = new Dictionary<string, string>
        {
            {"AD", _localizer["AD"]},
            {"AE", _localizer["AE"]},
            {"AF", _localizer["AF"]},
            {"AG", _localizer["AG"]},
            {"AI", _localizer["AI"]},
            {"AL", _localizer["AL"]},
            {"AM", _localizer["AM"]},
            {"AO", _localizer["AO"]},
            {"AQ", _localizer["AQ"]},
            {"AR", _localizer["AR"]},
            {"AS", _localizer["AS"]},
            {"AT", _localizer["AT"]},
            {"AU", _localizer["AU"]},
            {"AW", _localizer["AW"]},
            {"AX", _localizer["AX"]},
            {"AZ", _localizer["AZ"]},
            {"BA", _localizer["BA"]},
            {"BB", _localizer["BB"]},
            {"BD", _localizer["BD"]},
            {"BE", _localizer["BE"]},
            {"BF", _localizer["BF"]},
            {"BG", _localizer["BG"]},
            {"BH", _localizer["BH"]},
            {"BI", _localizer["BI"]},
            {"BJ", _localizer["BJ"]},
            {"BL", _localizer["BL"]},
            {"BM", _localizer["BM"]},
            {"BN", _localizer["BN"]},
            {"BO", _localizer["BO"]},
            {"BQ", _localizer["BQ"]},
            {"BR", _localizer["BR"]},
            {"BS", _localizer["BS"]},
            {"BT", _localizer["BT"]},
            {"BV", _localizer["BV"]},
            {"BW", _localizer["BW"]},
            {"BY", _localizer["BY"]},
            {"BZ", _localizer["BZ"]},
            {"CA", _localizer["CA"]},
            {"CC", _localizer["CC"]},
            {"CD", _localizer["CD"]},
            {"CF", _localizer["CF"]},
            {"CG", _localizer["CG"]},
            {"CH", _localizer["CH"]},
            {"CI", _localizer["CI"]},
            {"CK", _localizer["CK"]},
            {"CL", _localizer["CL"]},
            {"CM", _localizer["CM"]},
            {"CN", _localizer["CN"]},
            {"CO", _localizer["CO"]},
            {"CR", _localizer["CR"]},
            {"CU", _localizer["CU"]},
            {"CV", _localizer["CV"]},
            {"CW", _localizer["CW"]},
            {"CX", _localizer["CX"]},
            {"CY", _localizer["CY"]},
            {"CZ", _localizer["CZ"]},
            {"DE", _localizer["DE"]},
            {"DJ", _localizer["DJ"]},
            {"DK", _localizer["DK"]},
            {"DM", _localizer["DM"]},
            {"DO", _localizer["DO"]},
            {"DZ", _localizer["DZ"]},
            {"EC", _localizer["EC"]},
            {"EE", _localizer["EE"]},
            {"EG", _localizer["EG"]},
            {"EH", _localizer["EH"]},
            {"ER", _localizer["ER"]},
            {"ES", _localizer["ES"]},
            {"ET", _localizer["ET"]},
            {"FI", _localizer["FI"]},
            {"FJ", _localizer["FJ"]},
            {"FK", _localizer["FK"]},
            {"FM", _localizer["FM"]},
            {"FO", _localizer["FO"]},
            {"FR", _localizer["FR"]},
            {"GA", _localizer["GA"]},
            {"GB", _localizer["GB"]},
            {"GD", _localizer["GD"]},
            {"GE", _localizer["GE"]},
            {"GF", _localizer["GF"]},
            {"GG", _localizer["GG"]},
            {"GH", _localizer["GH"]},
            {"GI", _localizer["GI"]},
            {"GL", _localizer["GL"]},
            {"GM", _localizer["GM"]},
            {"GN", _localizer["GN"]},
            {"GP", _localizer["GP"]},
            {"GQ", _localizer["GQ"]},
            {"GR", _localizer["GR"]},
            {"GS", _localizer["GS"]},
            {"GT", _localizer["GT"]},
            {"GU", _localizer["GU"]},
            {"GW", _localizer["GW"]},
            {"GY", _localizer["GY"]},
            {"HK", _localizer["HK"]},
            {"HM", _localizer["HM"]},
            {"HN", _localizer["HN"]},
            {"HR", _localizer["HR"]},
            {"HT", _localizer["HT"]},
            {"HU", _localizer["HU"]},
            {"ID", _localizer["ID"]},
            {"IE", _localizer["IE"]},
            {"IL", _localizer["IL"]},
            {"IM", _localizer["IM"]},
            {"IN", _localizer["IN"]},
            {"IO", _localizer["IO"]},
            {"IQ", _localizer["IQ"]},
            {"IR", _localizer["IR"]},
            {"IS", _localizer["IS"]},
            {"IT", _localizer["IT"]},
            {"JE", _localizer["JE"]},
            {"JM", _localizer["JM"]},
            {"JO", _localizer["JO"]},
            {"JP", _localizer["JP"]},
            {"KE", _localizer["KE"]},
            {"KG", _localizer["KG"]},
            {"KH", _localizer["KH"]},
            {"KI", _localizer["KI"]},
            {"KM", _localizer["KM"]},
            {"KN", _localizer["KN"]},
            {"KP", _localizer["KP"]},
            {"KR", _localizer["KR"]},
            {"KW", _localizer["KW"]},
            {"KY", _localizer["KY"]},
            {"KZ", _localizer["KZ"]},
            {"LA", _localizer["LA"]},
            {"LB", _localizer["LB"]},
            {"LC", _localizer["LC"]},
            {"LI", _localizer["LI"]},
            {"LK", _localizer["LK"]},
            {"LR", _localizer["LR"]},
            {"LS", _localizer["LS"]},
            {"LT", _localizer["LT"]},
            {"LU", _localizer["LU"]},
            {"LV", _localizer["LV"]},
            {"LY", _localizer["LY"]},
            {"MA", _localizer["MA"]},
            {"MC", _localizer["MC"]},
            {"MD", _localizer["MD"]},
            {"ME", _localizer["ME"]},
            {"MF", _localizer["MF"]},
            {"MG", _localizer["MG"]},
            {"MH", _localizer["MH"]},
            {"MK", _localizer["MK"]},
            {"ML", _localizer["ML"]},
            {"MM", _localizer["MM"]},
            {"MN", _localizer["MN"]},
            {"MO", _localizer["MO"]},
            {"MP", _localizer["MP"]},
            {"MQ", _localizer["MQ"]},
            {"MR", _localizer["MR"]},
            {"MS", _localizer["MS"]},
            {"MT", _localizer["MT"]},
            {"MU", _localizer["MU"]},
            {"MV", _localizer["MV"]},
            {"MW", _localizer["MW"]},
            {"MX", _localizer["MX"]},
            {"MY", _localizer["MY"]},
            {"MZ", _localizer["MZ"]},
            {"NA", _localizer["NA"]},
            {"NC", _localizer["NC"]},
            {"NE", _localizer["NE"]},
            {"NF", _localizer["NF"]},
            {"NG", _localizer["NG"]},
            {"NI", _localizer["NI"]},
            {"NL", _localizer["NL"]},
            {"NO", _localizer["NO"]},
            {"NP", _localizer["NP"]},
            {"NR", _localizer["NR"]},
            {"NU", _localizer["NU"]},
            {"NZ", _localizer["NZ"]},
            {"OM", _localizer["OM"]},
            {"PA", _localizer["PA"]},
            {"PE", _localizer["PE"]},
            {"PF", _localizer["PF"]},
            {"PG", _localizer["PG"]},
            {"PH", _localizer["PH"]},
            {"PK", _localizer["PK"]},
            {"PL", _localizer["PL"]},
            {"PM", _localizer["PM"]},
            {"PN", _localizer["PN"]},
            {"PR", _localizer["PR"]},
            {"PS", _localizer["PS"]},
            {"PT", _localizer["PT"]},
            {"PW", _localizer["PW"]},
            {"PY", _localizer["PY"]},
            {"QA", _localizer["QA"]},
            {"RE", _localizer["RE"]},
            {"RO", _localizer["RO"]},
            {"RS", _localizer["RS"]},
            {"RU", _localizer["RU"]},
            {"RW", _localizer["RW"]},
            {"SA", _localizer["SA"]},
            {"SB", _localizer["SB"]},
            {"SC", _localizer["SC"]},
            {"SD", _localizer["SD"]},
            {"SE", _localizer["SE"]},
            {"SG", _localizer["SG"]},
            {"SH", _localizer["SH"]},
            {"SI", _localizer["SI"]},
            {"SJ", _localizer["SJ"]},
            {"SK", _localizer["SK"]},
            {"SL", _localizer["SL"]},
            {"SM", _localizer["SM"]},
            {"SN", _localizer["SN"]},
            {"SO", _localizer["SO"]},
            {"SR", _localizer["SR"]},
            {"SS", _localizer["SS"]},
            {"ST", _localizer["ST"]},
            {"SV", _localizer["SV"]},
            {"SX", _localizer["SX"]},
            {"SY", _localizer["SY"]},
            {"SZ", _localizer["SZ"]},
            {"TC", _localizer["TC"]},
            {"TD", _localizer["TD"]},
            {"TF", _localizer["TF"]},
            {"TG", _localizer["TG"]},
            {"TH", _localizer["TH"]},
            {"TJ", _localizer["TJ"]},
            {"TK", _localizer["TK"]},
            {"TL", _localizer["TL"]},
            {"TM", _localizer["TM"]},
            {"TN", _localizer["TN"]},
            {"TO", _localizer["TO"]},
            {"TR", _localizer["TR"]},
            {"TT", _localizer["TT"]},
            {"TV", _localizer["TV"]},
            {"TW", _localizer["TW"]},
            {"TZ", _localizer["TZ"]},
            {"UA", _localizer["UA"]},
            {"UG", _localizer["UG"]},
            {"UM", _localizer["UM"]},
            {"US", _localizer["US"]},
            {"UY", _localizer["UY"]},
            {"UZ", _localizer["UZ"]},
            {"VA", _localizer["VA"]},
            {"VC", _localizer["VC"]},
            {"VE", _localizer["VE"]},
            {"VG", _localizer["VG"]},
            {"VI", _localizer["VI"]},
            {"VN", _localizer["VN"]},
            {"VU", _localizer["VU"]},
            {"WF", _localizer["WF"]},
            {"WS", _localizer["WS"]},
            {"YE", _localizer["YE"]},
            {"YT", _localizer["YT"]},
            {"ZA", _localizer["ZA"]},
            {"ZM", _localizer["ZM"]},
            {"ZW", _localizer["ZW"]}
        };
        
        return countries.OrderBy(c => c.Value).ToDictionary(x => x.Key, x => x.Value);
    }
    
    public string GetCountryName(string countryCode)
    {
        var countries = GetCountries();
        return countries.ContainsKey(countryCode) ? countries[countryCode] : countryCode;
    }
    
    public string GetDefaultCountryCode()
    {
        return "DE"; // Germany
    }
}