using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenoCRM.Migrations
{
    /// <inheritdoc />
    public partial class ReplaceLoanSystemWithProjects : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Drop old SubordinatedLoans system if it exists (may not exist in all environments)
            migrationBuilder.Sql("""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_Payments_SubordinatedLoans_SubordinatedLoanId') THEN
                        ALTER TABLE "Payments" DROP CONSTRAINT "FK_Payments_SubordinatedLoans_SubordinatedLoanId";
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "LoanInterests";
                DROP TABLE IF EXISTS "SubordinatedLoans";
                """);

            // Rename column if old name exists, otherwise add the new column if missing
            migrationBuilder.Sql("""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Payments' AND column_name = 'SubordinatedLoanId') THEN
                        ALTER TABLE "Payments" RENAME COLUMN "SubordinatedLoanId" TO "LoanSubscriptionId";
                    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Payments' AND column_name = 'LoanSubscriptionId') THEN
                        ALTER TABLE "Payments" ADD COLUMN "LoanSubscriptionId" integer;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Payments_SubordinatedLoanId') THEN
                        ALTER INDEX "IX_Payments_SubordinatedLoanId" RENAME TO "IX_Payments_LoanSubscriptionId";
                    ELSIF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Payments_LoanSubscriptionId') THEN
                        CREATE INDEX "IX_Payments_LoanSubscriptionId" ON "Payments" ("LoanSubscriptionId");
                    END IF;
                END $$;
                """);

            // Create new tables (IF NOT EXISTS for idempotency)
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "LoanProjects" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Title" character varying(200) NOT NULL,
                    "ProjectNumber" character varying(50) NOT NULL,
                    "StartDate" timestamp without time zone NOT NULL,
                    "FinancingAmount" numeric(18,2) NOT NULL,
                    "Status" character varying(20) NOT NULL,
                    "Description" text,
                    "Notes" text,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "PK_LoanProjects" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "LoanOffers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LoanProjectId" integer NOT NULL,
                    "Title" character varying(200) NOT NULL,
                    "InterestRate" numeric(5,4) NOT NULL,
                    "TermMonths" integer NOT NULL,
                    "PaymentInterval" character varying(20) NOT NULL,
                    "RepaymentType" character varying(20) NOT NULL,
                    "GracePeriodMonths" integer NOT NULL DEFAULT 0,
                    "MinSubscriptionAmount" numeric(18,2),
                    "MaxSubscriptionAmount" numeric(18,2),
                    "Status" character varying(20) NOT NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "PK_LoanOffers" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_LoanOffers_LoanProjects_LoanProjectId" FOREIGN KEY ("LoanProjectId") REFERENCES "LoanProjects" ("Id") ON DELETE CASCADE
                );
                """);

            // Add GracePeriodMonths column if table existed but column is missing
            migrationBuilder.Sql("""
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'LoanOffers' AND column_name = 'GracePeriodMonths') THEN
                        ALTER TABLE "LoanOffers" ADD COLUMN "GracePeriodMonths" integer NOT NULL DEFAULT 0;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "LoanSubscriptions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LoanOfferId" integer NOT NULL,
                    "MemberId" integer NOT NULL,
                    "SubscriptionNumber" character varying(50) NOT NULL,
                    "SubscriptionDate" timestamp without time zone NOT NULL,
                    "Amount" numeric(18,2) NOT NULL,
                    "PaidInDate" timestamp without time zone,
                    "Status" character varying(20) NOT NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "PK_LoanSubscriptions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_LoanSubscriptions_LoanOffers_LoanOfferId" FOREIGN KEY ("LoanOfferId") REFERENCES "LoanOffers" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_LoanSubscriptions_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE CASCADE
                );
                """);

            // Add PaidInDate column if table existed but column is missing
            migrationBuilder.Sql("""
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'LoanSubscriptions' AND column_name = 'PaidInDate') THEN
                        ALTER TABLE "LoanSubscriptions" ADD COLUMN "PaidInDate" timestamp without time zone;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "LoanPaymentPlans" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LoanSubscriptionId" integer NOT NULL,
                    "GeneratedAt" timestamp without time zone NOT NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "PK_LoanPaymentPlans" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_LoanPaymentPlans_LoanSubscriptions_LoanSubscriptionId" FOREIGN KEY ("LoanSubscriptionId") REFERENCES "LoanSubscriptions" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "LoanPaymentPlanEntries" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LoanPaymentPlanId" integer NOT NULL,
                    "PeriodNumber" integer NOT NULL,
                    "DueDate" timestamp without time zone NOT NULL,
                    "PrincipalAmount" numeric(18,2) NOT NULL,
                    "InterestAmount" numeric(18,2) NOT NULL,
                    "TotalAmount" numeric(18,2) NOT NULL,
                    "RemainingBalance" numeric(18,2) NOT NULL,
                    "Status" character varying(20) NOT NULL,
                    "PaidDate" timestamp without time zone,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    CONSTRAINT "PK_LoanPaymentPlanEntries" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_LoanPaymentPlanEntries_LoanPaymentPlans_LoanPaymentPlanId" FOREIGN KEY ("LoanPaymentPlanId") REFERENCES "LoanPaymentPlans" ("Id") ON DELETE CASCADE
                );
                """);

            // Create indexes (IF NOT EXISTS)
            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_LoanOffers_LoanProjectId" ON "LoanOffers" ("LoanProjectId");
                CREATE INDEX IF NOT EXISTS "IX_LoanOffers_Status" ON "LoanOffers" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_LoanPaymentPlanEntries_DueDate" ON "LoanPaymentPlanEntries" ("DueDate");
                CREATE INDEX IF NOT EXISTS "IX_LoanPaymentPlanEntries_LoanPaymentPlanId" ON "LoanPaymentPlanEntries" ("LoanPaymentPlanId");
                CREATE INDEX IF NOT EXISTS "IX_LoanPaymentPlanEntries_Status" ON "LoanPaymentPlanEntries" ("Status");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_LoanPaymentPlans_LoanSubscriptionId" ON "LoanPaymentPlans" ("LoanSubscriptionId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_LoanProjects_ProjectNumber" ON "LoanProjects" ("ProjectNumber");
                CREATE INDEX IF NOT EXISTS "IX_LoanProjects_Status" ON "LoanProjects" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_LoanSubscriptions_LoanOfferId" ON "LoanSubscriptions" ("LoanOfferId");
                CREATE INDEX IF NOT EXISTS "IX_LoanSubscriptions_MemberId" ON "LoanSubscriptions" ("MemberId");
                CREATE INDEX IF NOT EXISTS "IX_LoanSubscriptions_Status" ON "LoanSubscriptions" ("Status");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_LoanSubscriptions_SubscriptionNumber" ON "LoanSubscriptions" ("SubscriptionNumber");
                """);

            // Add FK from Payments to LoanSubscriptions (if not exists)
            migrationBuilder.Sql("""
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_Payments_LoanSubscriptions_LoanSubscriptionId') THEN
                        ALTER TABLE "Payments" ADD CONSTRAINT "FK_Payments_LoanSubscriptions_LoanSubscriptionId"
                            FOREIGN KEY ("LoanSubscriptionId") REFERENCES "LoanSubscriptions" ("Id") ON DELETE SET NULL;
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Payments_LoanSubscriptions_LoanSubscriptionId",
                table: "Payments");

            migrationBuilder.DropTable(
                name: "LoanPaymentPlanEntries");

            migrationBuilder.DropTable(
                name: "LoanPaymentPlans");

            migrationBuilder.DropTable(
                name: "LoanSubscriptions");

            migrationBuilder.DropTable(
                name: "LoanOffers");

            migrationBuilder.DropTable(
                name: "LoanProjects");

            migrationBuilder.RenameColumn(
                name: "LoanSubscriptionId",
                table: "Payments",
                newName: "SubordinatedLoanId");

            migrationBuilder.RenameIndex(
                name: "IX_Payments_LoanSubscriptionId",
                table: "Payments",
                newName: "IX_Payments_SubordinatedLoanId");

            migrationBuilder.CreateTable(
                name: "SubordinatedLoans",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    MemberId = table.Column<int>(type: "integer", nullable: false),
                    Amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    CurrentValue = table.Column<decimal>(type: "numeric(18,2)", nullable: true),
                    EarlyTerminationDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    InterestRate = table.Column<decimal>(type: "numeric(5,4)", nullable: false),
                    IssueDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    LoanNumber = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    MaturityDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    Notes = table.Column<string>(type: "text", nullable: true),
                    NoticePeriodDays = table.Column<int>(type: "integer", nullable: true),
                    Status = table.Column<int>(type: "integer", nullable: false),
                    Terms = table.Column<string>(type: "text", nullable: true),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp without time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SubordinatedLoans", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SubordinatedLoans_Members_MemberId",
                        column: x => x.MemberId,
                        principalTable: "Members",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "LoanInterests",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    SubordinatedLoanId = table.Column<int>(type: "integer", nullable: false),
                    Amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    Notes = table.Column<string>(type: "text", nullable: true),
                    PaymentDate = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                    PeriodEnd = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    PeriodStart = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    Rate = table.Column<decimal>(type: "numeric(5,4)", nullable: false),
                    Status = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LoanInterests", x => x.Id);
                    table.ForeignKey(
                        name: "FK_LoanInterests_SubordinatedLoans_SubordinatedLoanId",
                        column: x => x.SubordinatedLoanId,
                        principalTable: "SubordinatedLoans",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_LoanInterests_SubordinatedLoanId",
                table: "LoanInterests",
                column: "SubordinatedLoanId");

            migrationBuilder.CreateIndex(
                name: "IX_SubordinatedLoans_LoanNumber",
                table: "SubordinatedLoans",
                column: "LoanNumber",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_SubordinatedLoans_MaturityDate",
                table: "SubordinatedLoans",
                column: "MaturityDate");

            migrationBuilder.CreateIndex(
                name: "IX_SubordinatedLoans_MemberId",
                table: "SubordinatedLoans",
                column: "MemberId");

            migrationBuilder.CreateIndex(
                name: "IX_SubordinatedLoans_Status",
                table: "SubordinatedLoans",
                column: "Status");

            migrationBuilder.AddForeignKey(
                name: "FK_Payments_SubordinatedLoans_SubordinatedLoanId",
                table: "Payments",
                column: "SubordinatedLoanId",
                principalTable: "SubordinatedLoans",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
